In [1]:
import pandas as pd

pd.set_option("display.max_colwidth", None)
df = pd.read_parquet("../data/processed/tweets_ai_sentiment_hf.parquet")

df.head(10)

,id,conversation_id,created_at,date,time,timezone,tweet,language,urls,photos,...,video,thumbnail,dominios_url,tipo_fuente_url,tweet_clean,tweet_clean_filt,num_palabras_filt,tweet_hf,sentiment_label_hf,sentiment_score_hf
0,826580756675694720,826580756675694720,2017-01-31 18:59:44,2017-01-31,18:59:44,-400,What topic could spark human dialogue on AI? Artificial Intelligence Glossary for Marketers https://t.co/SPyvplngtg @hubspot @Megan_Conley_,en,[https://blog.hubspot.com/marketing/artificial-intelligence-glossary-marketers],[],...,0,None,[blog.hubspot.com],[news],what topic could spark human dialogue on ai artificial intelligence glossary for marketers,what topic could spark human dialogue on ai artificial intelligence glossary for marketers,13,What topic could spark human dialogue on AI? Artificial Intelligence Glossary for Marketers http @user @user,neutral,0.722622
1,826580719921152000,826580719921152000,2017-01-31 18:59:35,2017-01-31,18:59:35,-400,"I think #ArtificialIntelligence will augment humanity, way before it displaces it. #AI #ChasmWaxing https://t.co/SAsmyqEe2b",en,[http://bit.ly/2bWb1ly],[],...,0,None,[bit.ly],[other],i think artificialintelligence will augment humanity way before it displaces it ai chasmwaxing,i think will augment humanity way before it displaces it,10,"I think #ArtificialIntelligence will augment humanity, way before it displaces it. #AI #ChasmWaxing http",positive,0.562817
2,826580631366700928,826580631366700928,2017-01-31 18:59:14,2017-01-31,18:59:14,-400,What Managers Need to Know About Artificial Intelligence https://t.co/t6VjDcGONz via @mitsmr,en,[http://mitsmr.com/2klQ17D],[],...,0,None,[mitsmr.com],[news],what managers need to know about artificial intelligence via,what managers need to know about artificial intelligence via,9,What Managers Need to Know About Artificial Intelligence http via @user,neutral,0.845438
3,826580578954780672,826580578954780672,2017-01-31 18:59:01,2017-01-31,18:59:01,-400,4 ways Artificial Intelligence changes the game for SEO https://t.co/uJnUtUSa2E #thenextweb,en,[http://bit.ly/2koUCIB],[],...,0,None,[bit.ly],[other],4 ways artificial intelligence changes the game for seo thenextweb,4 ways artificial intelligence changes the game for seo,9,4 ways Artificial Intelligence changes the game for SEO http #thenextweb,neutral,0.593140
4,826580577457287040,826580577457287040,2017-01-31 18:59:01,2017-01-31,18:59:01,-400,Artificial Intelligence can Shape the Future of Society https://t.co/LOPLuWPt8W | follow @whyfuture_AI,en,[https://www.youtube.com/watch?v=NQefTsrSjJY],[],...,0,None,[youtube.com],[social],artificial intelligence can shape the future of society follow,artificial intelligence can shape the future of society follow,9,Artificial Intelligence can Shape the Future of Society http | follow @user,positive,0.610682
5,826580175248699520,826580175248699520,2017-01-31 18:57:25,2017-01-31,18:57:25,-400,IBM #Watson uses artificial intelligence to create rum that tastes like a holiday https://t.co/XtxV3aYADa https://t.co/Lg8Lc0KOGX,en,[http://bit.ly/2kO88U7],[https://pbs.twimg.com/media/C3iaSR9UEAAEDW5.jpg],...,1,https://pbs.twimg.com/media/C3iaSR9UEAAEDW5.jpg,[bit.ly],[other],ibm watson uses artificial intelligence to create rum that tastes like a holiday,ibm uses artificial intelligence to create rum that tastes like a holiday,12,IBM #Watson uses artificial intelligence to create rum that tastes like a holiday http http,positive,0.567571
6,826580141543415808,826580141543415808,2017-01-31 18:57:17,2017-01-31,18:57:17,-400,How Artificial Intelligence Will Revolutionize eDiscovery https://t.co/elT5C0xm0N https://t.co/OvoqxjkvgK,en,[http://upflow.co/l/45Ug],[https://pbs.twimg.com/media/C3iaQfkWQAAqKDv.jpg],...,1,https://pbs.twimg.com/media/C3iaQfkWQAAqKDv.jpg,[upflow.co],[other],how artificial intelligence will revolutionize ediscovery,how artificial intelligence will revolutionize ediscovery,6,How Artificial Intelligence Will Revolutionize eDiscovery http http,neutral,0.559166
7,826580101148135424,826580101148135424,2017-01-31 18:57:07,2017-01-31,18:57:07,-400,How Artificial Intelligence Will Kickstart the Internet of Things #Nitaipartners #internetofthings #bigdataanalytic… https://t.co/Hcp6VPQF4C,en,[http://buff.ly/2kJMRht],[],...,0,None,[buff.ly],[other],how artificial intelligence will kickstart the internet of things nitaipartners internetofthings bigdataanalytic,how artificial intelligence will kickstart the internet of things,9,How Artificial Intelligence Will Kickstart the Internet of Things #Nitaipartners #internetofthings #bigdataanalytic… http,neutral,0.552606
8,826580083519397760,826580083519397760,2017-01-31 18:57:03,2017-01-31,18:57:03,-400,This man is not mentally all there. That or he's actually artificial intelligence that's not that intelligent. He makes C-3PO look smart.🙄😒 https://t.co/42m4kGG3NY,en,[https://twitter.com/tommyxtopher/status/826521935987298304],[],...,0,None,[twitter.com],[social],this man is not mentally all there that or he s actually artificial intelligence that s not that intelligent he makes c 3po look smart 🙄😒,this man is not mentally all there that or he s actually artificial intelligence that s not that intelligent he makes c 3po look smart,25,This man is not mentally all there. That or he's actually artificial intelligence that's not that intelligent. He makes C-3PO look smart.🙄😒 http,negative,0.894269
9,826579782292889600,826579782292889600,2017-01-31 18:55:51,2017-01-31,18:55:51,-400,Modular housing and artificial intelligence among ideas recognized at STEM awards https://t.co/RDObQjMjAE,en,[http://upflow.co/l/NaTn],[],...,0,None,[upflow.co],[other],modular housing and artificial intelligence among ideas recognized at stem awards,modular housing and artificial intelligence among ideas recognized at stem awards,11,Modular housing and artificial intelligence among ideas recognized at STEM awards http,positive,0.482768

In [2]:
df.groupby("sentiment_label_hf")["sentiment_score_hf"].describe()

,count,mean,std,min,25%,50%,75%,max
sentiment_label_hf,,,,,,,,
negative,60685.0,0.696451,0.146393,0.335874,0.574480,0.704215,0.822754,0.965639
neutral,604228.0,0.687425,0.124707,0.334364,0.584402,0.688961,0.789428,0.956674
positive,196203.0,0.619184,0.111969,0.336274,0.529629,0.596017,0.689116,0.957266

In [4]:
df["sentiment_extreme"] = (
    (df["sentiment_label_hf"] != "neutral") &
    (df["sentiment_score_hf"] > 0.9)
)
df.head(10)

,id,conversation_id,created_at,date,time,timezone,tweet,language,urls,photos,...,thumbnail,dominios_url,tipo_fuente_url,tweet_clean,tweet_clean_filt,num_palabras_filt,tweet_hf,sentiment_label_hf,sentiment_score_hf,sentiment_extreme
0,826580756675694720,826580756675694720,2017-01-31 18:59:44,2017-01-31,18:59:44,-400,What topic could spark human dialogue on AI? Artificial Intelligence Glossary for Marketers https://t.co/SPyvplngtg @hubspot @Megan_Conley_,en,[https://blog.hubspot.com/marketing/artificial-intelligence-glossary-marketers],[],...,None,[blog.hubspot.com],[news],what topic could spark human dialogue on ai artificial intelligence glossary for marketers,what topic could spark human dialogue on ai artificial intelligence glossary for marketers,13,What topic could spark human dialogue on AI? Artificial Intelligence Glossary for Marketers http @user @user,neutral,0.722622,False
1,826580719921152000,826580719921152000,2017-01-31 18:59:35,2017-01-31,18:59:35,-400,"I think #ArtificialIntelligence will augment humanity, way before it displaces it. #AI #ChasmWaxing https://t.co/SAsmyqEe2b",en,[http://bit.ly/2bWb1ly],[],...,None,[bit.ly],[other],i think artificialintelligence will augment humanity way before it displaces it ai chasmwaxing,i think will augment humanity way before it displaces it,10,"I think #ArtificialIntelligence will augment humanity, way before it displaces it. #AI #ChasmWaxing http",positive,0.562817,False
2,826580631366700928,826580631366700928,2017-01-31 18:59:14,2017-01-31,18:59:14,-400,What Managers Need to Know About Artificial Intelligence https://t.co/t6VjDcGONz via @mitsmr,en,[http://mitsmr.com/2klQ17D],[],...,None,[mitsmr.com],[news],what managers need to know about artificial intelligence via,what managers need to know about artificial intelligence via,9,What Managers Need to Know About Artificial Intelligence http via @user,neutral,0.845438,False
3,826580578954780672,826580578954780672,2017-01-31 18:59:01,2017-01-31,18:59:01,-400,4 ways Artificial Intelligence changes the game for SEO https://t.co/uJnUtUSa2E #thenextweb,en,[http://bit.ly/2koUCIB],[],...,None,[bit.ly],[other],4 ways artificial intelligence changes the game for seo thenextweb,4 ways artificial intelligence changes the game for seo,9,4 ways Artificial Intelligence changes the game for SEO http #thenextweb,neutral,0.593140,False
4,826580577457287040,826580577457287040,2017-01-31 18:59:01,2017-01-31,18:59:01,-400,Artificial Intelligence can Shape the Future of Society https://t.co/LOPLuWPt8W | follow @whyfuture_AI,en,[https://www.youtube.com/watch?v=NQefTsrSjJY],[],...,None,[youtube.com],[social],artificial intelligence can shape the future of society follow,artificial intelligence can shape the future of society follow,9,Artificial Intelligence can Shape the Future of Society http | follow @user,positive,0.610682,False
5,826580175248699520,826580175248699520,2017-01-31 18:57:25,2017-01-31,18:57:25,-400,IBM #Watson uses artificial intelligence to create rum that tastes like a holiday https://t.co/XtxV3aYADa https://t.co/Lg8Lc0KOGX,en,[http://bit.ly/2kO88U7],[https://pbs.twimg.com/media/C3iaSR9UEAAEDW5.jpg],...,https://pbs.twimg.com/media/C3iaSR9UEAAEDW5.jpg,[bit.ly],[other],ibm watson uses artificial intelligence to create rum that tastes like a holiday,ibm uses artificial intelligence to create rum that tastes like a holiday,12,IBM #Watson uses artificial intelligence to create rum that tastes like a holiday http http,positive,0.567571,False
6,826580141543415808,826580141543415808,2017-01-31 18:57:17,2017-01-31,18:57:17,-400,How Artificial Intelligence Will Revolutionize eDiscovery https://t.co/elT5C0xm0N https://t.co/OvoqxjkvgK,en,[http://upflow.co/l/45Ug],[https://pbs.twimg.com/media/C3iaQfkWQAAqKDv.jpg],...,https://pbs.twimg.com/media/C3iaQfkWQAAqKDv.jpg,[upflow.co],[other],how artificial intelligence will revolutionize ediscovery,how artificial intelligence will revolutionize ediscovery,6,How Artificial Intelligence Will Revolutionize eDiscovery http http,neutral,0.559166,False
7,826580101148135424,826580101148135424,2017-01-31 18:57:07,2017-01-31,18:57:07,-400,How Artificial Intelligence Will Kickstart the Internet of Things #Nitaipartners #internetofthings #bigdataanalytic… https://t.co/Hcp6VPQF4C,en,[http://buff.ly/2kJMRht],[],...,None,[buff.ly],[other],how artificial intelligence will kickstart the internet of things nitaipartners internetofthings bigdataanalytic,how artificial intelligence will kickstart the internet of things,9,How Artificial Intelligence Will Kickstart the Internet of Things #Nitaipartners #internetofthings #bigdataanalytic… http,neutral,0.552606,False
8,826580083519397760,826580083519397760,2017-01-31 18:57:03,2017-01-31,18:57:03,-400,This man is not mentally all there. That or he's actually artificial intelligence that's not that intelligent. He makes C-3PO look smart.🙄😒 https://t.co/42m4kGG3NY,en,[https://twitter.com/tommyxtopher/status/826521935987298304],[],...,None,[twitter.com],[social],this man is not mentally all there that or he s actually artificial intelligence that s not that intelligent he makes c 3po look smart 🙄😒,this man is not mentally all there that or he s actually artificial intelligence that s not that intelligent he makes c 3po look smart,25,This man is not mentally all there. That or he's actually artificial intelligence that's not that intelligent. He makes C-3PO look smart.🙄😒 http,negative,0.894269,False
9,826579782292889600,826579782292889600,2017-01-31 18:55:51,2017-01-31,18:55:51,-400,Modular housing and artificial intelligence among ideas recognized at STEM awards https://t.co/RDObQjMjAE,en,[http://upflow.co/l/NaTn],[],...,None,[upflow.co],[other],modular housing and artificial intelligence among ideas recognized at stem awards,modular housing and artificial intelligence among ideas recognized at stem awards,11,Modular housing and artificial intelligence among ideas recognized at STEM awards http,positive,0.482768,False

In [5]:
pd.crosstab(df["language"], df["sentiment_label_hf"], normalize="index")

sentiment_label_hf  negative   neutral  positive
language
am                  0.000000  0.333333  0.666667
ar                  0.081633  0.428571  0.489796
bg                  0.000000  0.800000  0.200000
bn                  0.000000  1.000000  0.000000
ca                  0.028506  0.919042  0.052452
cs                  0.023649  0.871622  0.104730
cy                  0.000000  0.938776  0.061224
da                  0.044508  0.902778  0.052715
de                  0.048772  0.844393  0.106835
el                  0.133333  0.733333  0.133333
en                  0.071590  0.695959  0.232450
es                  0.038544  0.750538  0.210918
et                  0.097959  0.828571  0.073469
eu                  0.000000  1.000000  0.000000
fa                  0.375000  0.312500  0.312500
fi                  0.073620  0.742331  0.184049
fr                  0.032672  0.851656  0.115672
hi                  0.513514  0.337838  0.148649
ht                  0.021739  0.891304  0.086957
hu                  0.083333  0.916667  0.000000
hy                  0.000000  0.200000  0.800000
in                  0.115346  0.674524  0.210130
is                  0.000000  1.000000  0.000000
it                  0.065808  0.716981  0.217211
iw                  0.000000  1.000000  0.000000
ja                  0.055270  0.823907  0.120823
ko                  0.065574  0.737705  0.196721
lt                  0.009346  0.943925  0.046729
lv                  0.000000  0.909091  0.090909
ne                  0.142857  0.714286  0.142857
nl                  0.044187  0.790637  0.165176
no                  0.062500  0.800000  0.137500
pl                  0.121711  0.733553  0.144737
pt                  0.064835  0.714286  0.220879
ro                  0.015657  0.923737  0.060606
ru                  0.050000  0.750000  0.200000
si                  0.000000  1.000000  0.000000
sl                  0.153846  0.769231  0.076923
sv                  0.060150  0.699248  0.240602
ta                  0.125000  0.875000  0.000000
th                  0.084507  0.732394  0.183099
tl                  0.160287  0.722488  0.117225
tr                  0.111842  0.673246  0.214912
uk                  0.000000  1.000000  0.000000
und                 0.056647  0.797688  0.145665
ur                  0.400000  0.600000  0.000000
vi                  0.077778  0.855556  0.066667
zh                  0.043243  0.805405  0.151351

In [6]:
df.groupby(df["created_at"].dt.year)["sentiment_label_hf"].value_counts(normalize=True)

created_at  sentiment_label_hf
2017        neutral               0.736668
            positive              0.195373
            negative              0.067959
2018        neutral               0.685904
            positive              0.247688
            negative              0.066407
2019        neutral               0.675805
            positive              0.249992
            negative              0.074204
2020        neutral               0.689301
            positive              0.236381
            negative              0.074318
2021        neutral               0.671668
            positive              0.239033
            negative              0.089298
Name: proportion, dtype: float64